#!/usr/bin/env python3
"""Interactive .env setup — run once before starting the bot.

    python scripts/setup_wizard.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / ".env"


def _prompt(name: str, hint: str, *, secret: bool = False, optional: bool = False) -> str:
    opt = " (optional, Enter to skip)" if optional else ""
    print(f"\n{hint}{opt}")
    return input(f"  {name}: ").strip()


def _valid_discord_id(value: str) -> bool:
    return bool(re.fullmatch(r"\d{17,20}", value))


def main() -> int:
    print("Companion — .env setup wizard")
    print("=" * 40)
    print("\nRequired: Discord bot token + OpenAI key")
    print("Owners: at least one of numeric ID(s) or username(s), e.g. cm6550")

    token = _prompt(
        "DISCORD_TOKEN",
        "Discord bot token:",
        secret=True,
    )
    api_key = _prompt("OPENAI_API_KEY", "OpenAI API key (sk-...):", secret=True)

    owner_id = _prompt(
        "OWNER_DISCORD_ID",
        "Your numeric user ID (Developer Mode → Copy User ID):",
        optional=True,
    )
    owner_ids = _prompt(
        "OWNER_DISCORD_IDS",
        "Extra owner IDs, comma-separated:",
        optional=True,
    )
    usernames = _prompt(
        "OWNER_USERNAMES",
        "Owner usernames (default cm6550 for reviewer):",
        optional=True,
    ) or "cm6550"

    test_guild = _prompt(
        "TEST_GUILD_ID",
        "Test server ID (right-click server → Copy Server ID):",
        optional=True,
    )
    test_channel = _prompt(
        "TEST_CHANNEL_ID",
        "Test channel ID (right-click #channel → Copy Channel ID):",
        optional=True,
    )

    errors = []
    if not token or len(token) < 20:
        errors.append("DISCORD_TOKEN looks too short")
    if not api_key.startswith("sk-"):
        errors.append("OPENAI_API_KEY should start with sk-")
    if owner_id and not _valid_discord_id(owner_id):
        errors.append("OWNER_DISCORD_ID must be 17–20 digits")
    if not owner_id and not owner_ids and not usernames:
        errors.append("Set at least one owner: ID(s) or OWNER_USERNAMES")

    if errors:
        print("\nProblems:")
        for e in errors:
            print(f"  - {e}")
        return 1

    lines = [
        "# Generated by setup_wizard.py",
        "",
        f"DISCORD_TOKEN={token}",
        f"OPENAI_API_KEY={api_key}",
        "",
        f"OWNER_USERNAMES={usernames}",
    ]
    if owner_id:
        lines.append(f"OWNER_DISCORD_ID={owner_id}")
    if owner_ids:
        lines.append(f"OWNER_DISCORD_IDS={owner_ids}")
    if test_guild:
        lines.append(f"TEST_GUILD_ID={test_guild}")
    if test_channel:
        lines.append(f"TEST_CHANNEL_ID={test_channel}")
    lines.extend(["", "OPENAI_MODEL=gpt-4o-mini", "BRAIN_DIR=./data/brain", ""])

    ENV_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nSaved {ENV_PATH}")
    print("\nNext:")
    print("  python scripts/check_setup.py")
    print("  .\\scripts\\start.ps1")
    print("\nSee SUBMISSION.md for GitHub + invite link + Loom.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
